Person inheritance
ann1777/JavaCourse2022 pull request #11
Opened 2022-06-08 16:28 UTC by ann1777

An example of classes inheritance and methods overriding

2022-06-08 20:05 UTC, taraskarpenko requested changes

2022-06-08 20:05 UTC, taraskarpenko commented on lesson16/src/main/java/inheritance/Person.java
> +    protected String maidenLastname;
Получается что это свойство будет и у мужчины и у женщины. В то время как в классе мужчина оно ни к чему.

2022-06-08 20:05 UTC, taraskarpenko commented on lesson16/src/main/java/inheritance/Person.java
> +    public void deregisterPartnership(boolean revertLastname, String maidenLastname) {
В классе мужчина этот метод смотрится несколько странно.

2022-06-08 20:05 UTC, taraskarpenko commented on lesson16/src/main/java/inheritance/Person.java
> +    public void registerPartnership(String lastname) {
А сможете сделать так что б сюда приходил тип Person, производилась проверка на противоположность пола, если проверка успешна то вызывался абстрактный метод setPartner(Person person)
И дальше в классе мужчина setPartner устанавливает себе свойство partner, и партнеру (доступному в методе) вызывал метод setPartner() передавая себя в качетсве параметра
А в классе женщины помимо таких действий еще и фамилии устанавливались как нужно.
Осторожно, можна свалиться в циклические вызовы, необходимо ставить дополнительные проверки

2022-06-08 20:05 UTC, taraskarpenko commented on lesson16/src/main/java/inheritance/Woman.java
> +        if(this.age >= 60) {
смотрите как тут можно вместо всего ИФ
System.out.printf("This woman is %s retired", age>=60 ? "" : "not");
return age>=60;

2022-06-08 20:05 UTC, taraskarpenko commented on lesson16/src/main/java/inheritance/Woman.java
> +        if (revertLastName == Boolean.TRUE) {
смотрите, внутри IF должно быть выражение которое в результате сведется к boolean, но у вас revertLastName уже boolean, поэтому можно писать просто 
if (revertLastName)

2022-06-08 20:05 UTC, taraskarpenko commented on lesson16/src/main/java/inheritance/Man.java
> +    @Override
Если метод в родителе не абстрактный, и в наследнике у него точно такое же поведение, то нет надобности переопределять

2022-06-08 20:15 UTC, ann1777 commented on lesson16/src/main/java/inheritance/Person.java
> +    protected String maidenLastname;
Класс Person учитывает так же нетрадиционные отношения, в этом случае смена фамилии может быть так же  и для мужчины

2022-06-08 20:16 UTC, ann1777 commented on lesson16/src/main/java/inheritance/Person.java
> +    public void deregisterPartnership(boolean revertLastname, String maidenLastname) {
Комментарий примерно такой же как и предыдущий

2022-06-08 20:40 UTC, taraskarpenko commented on lesson16/src/main/java/inheritance/Person.java
> +    protected String maidenLastname;
Аргумент принимается, но тогда стоит дать переменной более нейтральное название типа "birthLastName" или "previousLastName", а то maiden это все же дева/девушка :)

2022-06-08 20:46 UTC, ann1777 commented on lesson16/src/main/java/inheritance/Woman.java
> +        if(this.age >= 60) {
Супер. Так намного проще!

2022-06-09 18:44 UTC, ann1777 commented on lesson16/src/main/java/inheritance/Person.java
> +    protected String maidenLastname;
The field "maidenName" of the class Person renamed as "birthLastName" field.

2022-06-09 19:16 UTC, ann1777 commented on lesson16/src/main/java/inheritance/Person.java
> +    public void registerPartnership(String lastname) {
Done

2022-06-09 19:16 UTC, ann1777 commented on lesson16/src/main/java/inheritance/Woman.java
> +        if (revertLastName == Boolean.TRUE) {
done

2022-06-09 19:16 UTC, ann1777 commented on lesson16/src/main/java/inheritance/Man.java
> +    @Override
done

2022-06-10 21:37 UTC, taraskarpenko commented on lesson16/src/main/java/inheritance/Person.java
> +            this.setPartner(partner);
У вас this.setPartner(partner); делает то же самое this.partner = partner;
идея была как раз в том что б сделать 
partner.setPartner(this)

2022-06-10 21:40 UTC, taraskarpenko commented on lesson16/src/main/java/inheritance/Person.java
> +    public void deregisterPartnership(boolean revertLastname, String birthLastname) {
А как же 
this.partner.setPartner(null);
this.partner.setLastName(this.partner.getPreviousLasName())
this.partner = null;
А то фамилию назад поменяли

2022-06-13 11:43 UTC, merged