TestNG framework
ann1777/JavaCourse2022 pull request #13
Opened 2022-06-27 11:13 UTC by ann1777

Created TestPersonMan and TestPersonWoman classes with test methods.
Added testng.xml and testng1.xml files to run test suites.

2022-06-29 08:16 UTC, taraskarpenko commented on testPersonInheritance/src/test/java/TestPersonMan.java
> +public class TestPersonMan extends Person {
Тестовый класс может наследовать какой-то базовый тестовый класс, но наследовать его от какой либо бизнес модели не стоит. 
Тем более что такое наследование вам ничего не дает

2022-06-29 08:16 UTC, taraskarpenko commented on testPersonInheritance/testng.xml
> +        <groups>
Не увидел у вас нигде что б тесты были включены в какие-то группы, значит и тут они не нужны

2022-06-29 08:16 UTC, taraskarpenko commented on testPersonInheritance/src/test/java/TestPersonWoman.java
> +    private static Object getWoman1() {
В тестовом классе все эти методы не несут никакой пользы

2022-06-29 11:40 UTC, ann1777 commented on testPersonInheritance/src/test/java/TestPersonWoman.java
> +    private static Object getWoman1() {
У меня в testng1 есть группы:

2022-06-29 11:40 UTC, ann1777 commented on testPersonInheritance/src/test/java/TestPersonWoman.java
> +    private static Object getWoman1() {
<groups>
            <run>
                <include name="Man1"/>
                <include name="Man2"/>
            </run>
        </groups>

2022-06-29 11:45 UTC, ann1777 commented on testPersonInheritance/testng.xml
> +        <groups>
У меня в testng1 есть группы:
Man1, Man2 и Woman1, Woman2

2022-06-29 11:48 UTC, ann1777 commented on testPersonInheritance/src/test/java/TestPersonMan.java
> +public class TestPersonMan extends Person {
Я убрала это еще позавчера, и обновила пулреквест, но к сожалению у меня упал линукс и проверить я уже не успела.

2022-06-29 19:50 UTC, ann1777 commented on testPersonInheritance/src/test/java/TestPersonMan.java
> +public class TestPersonMan extends Person {
см. коммит [5668c76](https://github.com/ann1777/JavaCourse2022/pull/13/commits/5668c761542071038c92a6455b458fbb23a2600c)

2022-06-29 19:56 UTC, ann1777 commented on testPersonInheritance/testng.xml
> +        <groups>
Пробовала удалить теги <groups> тогда я не могу запускать тесты для Man1 и Man2, вылазит ошибка

2022-06-29 19:58 UTC, ann1777 commented on testPersonInheritance/src/test/java/TestPersonWoman.java
> +    private static Object getWoman1() {
Без  private static Object getWoman1() не работает код. Объекты woman1 и woman2 не создаются

2022-06-29 20:53 UTC, taraskarpenko requested changes
К сожалению не нашел провайдеров данных

2022-06-29 20:53 UTC, taraskarpenko commented on lesson20/src/TestPersonMan.java
> +    public void BeforeEachTest() {
Не начинайте имена методов с заглавной буквы

2022-06-29 20:53 UTC, taraskarpenko commented on lesson20/src/TestPersonMan.java
> +        man1.isRetired();
вы ж никак не проверяете возвращаемый результат.
тут бы Assert.assertFalse(man1.isRetired();)

2022-07-27 16:46 UTC, closed without merging

2022-08-06 10:48 UTC, ann1777 commented
Reopen pull-request