Created student.json, student.xml, student.yaml
ann1777/JavaCourse2022 pull request #2
Opened 2022-02-09 15:40 UTC by ann1777

2022-02-09 16:46 UTC, taraskarpenko requested changes

2022-02-09 16:46 UTC, taraskarpenko commented on student1.yaml
> +        first_semestr: math, physics
math, physics 
выглядит как список, но задан как простая строка "math, physics"
Уточните что именно имелось ввиду

2022-02-09 16:46 UTC, taraskarpenko commented on student1.yaml
> +      philosophy, history
то же самое, выглядит как список, но на самом деле строка

2022-02-09 17:04 UTC, ann1777 commented on student1.yaml
> +        first_semestr: math, physics
Items are represented as lists in student1.yaml:
https://github.com/ann1777/JavaCourse2022/commit/8d165630a7ef1356fc2cc953b515705df6f088d6

2022-02-09 17:04 UTC, ann1777 commented on student1.yaml
> +      philosophy, history
Items are represented as lists in student1.yaml:
https://github.com/ann1777/JavaCourse2022/commit/8d165630a7ef1356fc2cc953b515705df6f088d6

2022-02-09 18:15 UTC, taraskarpenko approved these changes

2022-02-17 12:31 UTC, ann1777 commented
Data srorage and data transfer format

2022-02-17 12:31 UTC, merged